"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const dynamic = 'force-dynamic'
export default function RootLayout({ children }) {
  const pathname = usePathname();
  console.log(pathname)

  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <main className="grid w-full h-full ">{
          pathname !== "/login" ?
            <div className="inline">
              <Sidebar />
            </div>
            : null
          }
          <div className="pl-[200px] p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
