import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <main className="grid w-full h-full ">
          <div className="inline ">
            <Sidebar />
          </div>
          <div className="pl-[200px] p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
